### ISSUE TITLE
Only pulls in data from one data set

### ISSUE THREAD

**Issue by antonioortegajr** [sheparddw/idx-broker#3]
This plugin is only pulling in a single data set regardless of the API key used.

**Comment by sheparddw** [comment]
I remember now. I had commented out the writing of the location lists and forgot to remove the comment markup. That should fix the issue. I can see in the morning.

**Comment by antonioortegajr** [comment]
I uncommented that and it works until I refresh the api calls to get a new data set. Then the auto compete no longer works.

**Comment by antonioortegajr** [comment]
Pull request made to fix this. Issue. Uncommented and fixed the file path there.

**Comment by sheparddw** [comment]
Fixed issue in latest commit.
