### ISSUE TITLE
Search is not relevant in certain data sets

### ISSUE THREAD

**Issue by antonioortegajr** [sheparddw/idx-broker#7]
Data sets for like for Los Angeles do not use the city field for many places. These are often not cities, but areas (example: Bel Air). However since most are searching areas (or subdivisions) this makes the city field search not very useful. The ability to use an advanced field instead of the city field would make this plugin useful in these markets.

**Comment by sheparddw** [comment]
This issue is fixed for the rewrite branch and will be merged into the master branch in a future update: https://github.com/sheparddw/idx-broker/commit/4564692517364b7088b3bdf4387898dced844905
