### ISSUE TITLE
failed to open stream

### ISSUE THREAD

**Issue by karlen1983** [sheparddw/idx-broker#8]
.../wp-content/plugins/idx-omnibar/assets/js/locationlist.json): failed to open stream: No such file or directory in .../wp-content/plugins/idx-omnibar-master/idx-omnibar-get-locations.php on line 56

IDX Broker is already installed, activated with the correct API Key and it is working OK

**Comment by sheparddw** [comment]
You must unzip, rename idx-omnibar-master to idx-omnibar, and rezip as instructed on the readme page before installing it in WordPress. This will resolve the issue.
